//lib/core/database/app_database.dart
import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

import 'tables/documents_table.dart';
import 'tables/bundles_table.dart';
import 'tables/bundle_documents_table.dart';
import 'models/document_type.dart';
// import daos for bundles and reminders here
import 'daos/documents_dao.dart';

part 'app_database.g.dart'; // This file will be generated by build_runner

@DriftDatabase(tables: [Documents, Bundles, BundleDocuments], daos: [DocumentsDao])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1; // Increment this when you change tables
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    // Name your database file pocket_vault.sqlite
    final file = File(p.join(dbFolder.path, 'pocket_vault.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}
